### ISSUE TITLE
Error 500 when querying specific mutation (NPE)

### ISSUE THREAD

**Issue by nr23730** [oncokb/oncokb#2055] opened 2020-05-14 13:05 UTC
Issue: 
We have a small test sample for cBioPortal containing three mutations that are being annotated using OncoKB when accessing the patient view. However, the proxy in cBioPortal fails with Error 500 (cBioPortal/cbioportal#7499) as OncoKB also fails with an Error 500 that is being caused by a nullpointer exception:

```
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.NullPointerException
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:977)
	org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:867)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:841)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:436)
	org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
```

Example:

Send a POST to `https://public.api.oncokb.org/api/v1/annotate/mutations/byProteinChange` with the following JSON-Body:
```
[
	{
		"alteration": "R248",
		"consequence": "Missense_Mutation",
		"gene": {
			"entrezGeneId": 7157
		},
		"id": "7157_Other_R248_Missense_Mutation",
		"proteinEnd": 248,
		"proteinStart": 248,
		"tumorType": "Other"
	}
]
```

Screenshot:
![grafik](https://user-images.githubusercontent.com/20756025/81937310-c43ac980-95f3-11ea-862b-29eaaef07429.png)

**Comment by zhx828** [comment] 2020-05-14 20:20
@nr23730 thanks for reporting the issue. I will try to fix that asap. But just a side node, this is not a missense mutation though. A positional variant instead. I guess it is a hypothetical test case?

**Comment by nr23730** [comment] 2020-05-14 21:50
Thank you for the quick response! I didn't create that test dataset, but you are probably right. 
Rother way: From a software engineering standpoint this shouldn't result in an exception. ;)

**Comment by zhx828** [comment] 2020-05-15 14:52
@nr23730 the issue is fixed by now. Please let me know if you see any other issues. :)

**Closed by zhx828** 2020-05-15 14:52 UTC
Labels: oncokb-core

**Comment by nr23730** [comment] 2020-05-15 15:09
> 
> 
> @nr23730 the issue is fixed by now. Please let me know if you see any other issues. :)

Thank you very much!
