### ISSUE TITLE
Send automated embargo email

### ISSUE THREAD

**Issue by benzuzu** [oncokb/oncokb#2629] opened 2021-06-29 21:42 UTC
- [x] Create embargo list in the property file
- [x] Try to identify whether the user comes from the country in the embargo list(look at the country data field)
- [x] When sending the user info to slack, give a warning if we can identify the user
- [x] Add an option in the slack to allow the team to deny the users and send the embargo email
- [x] Add an email record indicating we have sent the embargo email

- [x] do not include the user in weekly email

**Comment by zhx828** [comment] 2021-08-11 16:17
The issue is addressed in https://github.com/oncokb/oncokb-public/pull/676 . We do not have any instance that we need to send the embargo email yet. More to come.

**Closed** 2022-06-09 19:56 UTC
Labels: feature
